-- Wireframe app store (Postgres). Source of truth for PRD/spec DATA.
-- Rendered HTML artifacts are NOT stored here — they are regenerated by the CLI
-- into a gitignored scratch cache on every build. See docs: "스펙만 DB, HTML은 재생성".
--
-- Idempotent: safe to run on every server boot (create table if not exists).

create table if not exists projects (
  slug        text primary key,
  no          text,
  title       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists runs (
  run_id             text primary key,
  project_slug       text not null references projects(slug) on delete cascade,
  kind               text,
  no                 text,                 -- e.g. PRD-002
  title              text,
  status             text,                 -- draft | ready | confirmed | ...
  prd_version        integer not null default 1,
  artifact_count     integer not null default 0,
  asset_project_slug text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists runs_project_idx on runs (project_slug);

-- PRD input (input/vN.md), kept versioned so edits never destroy the prior text.
create table if not exists run_inputs (
  run_id     text not null references runs(run_id) on delete cascade,
  version    integer not null,
  content    text not null,
  created_at timestamptz not null default now(),
  primary key (run_id, version)
);

-- spec/*.json documents as JSONB, one row per (run, name).
-- name ∈ {domain, manifest, features, flow, clarifications, build-context, overrides, graph}.
-- overrides is the user-edit SSOT; the rest are generated (rebuilt from the PRD).
create table if not exists run_specs (
  run_id     text not null references runs(run_id) on delete cascade,
  name       text not null,
  data       jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (run_id, name)
);
