// One-off migration: wireFrame/index.json + runs/* files → Postgres.
// Idempotent (upserts), so re-running re-syncs from disk. HTML artifacts are skipped
// on purpose — they are regenerated by the build, not stored.
//
//   node scripts/import-to-db.mjs
//
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

// --- minimal .env loader (mirror of server/env.ts: do not override real env) ---
for (const name of [".env.local", ".env"]) {
  const file = path.join(root, name);
  if (!fs.existsSync(file)) continue;
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const m = /^([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line.trim());
    if (!m) continue;
    const [, key, raw] = m;
    const value = raw.replace(/^["']|["']$/g, "");
    if (!process.env[key]) process.env[key] = value;
  }
}

const url = process.env.DATABASE_URL;
if (!url) {
  console.error("DATABASE_URL 없음 (.env 확인)");
  process.exit(1);
}

const wireframeDir = path.join(root, "wireFrame");
const runsDir = path.join(wireframeDir, "runs");
const SPEC_NAMES = [
  "domain",
  "manifest",
  "features",
  "flow",
  "clarifications",
  "build-context",
  "overrides",
  "graph",
];

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

const pool = new pg.Pool({ connectionString: url });

async function main() {
  const schema = fs.readFileSync(path.join(root, "server", "schema.sql"), "utf8");
  await pool.query(schema);

  const index = readJson(path.join(wireframeDir, "index.json"));
  if (!index?.projects) {
    console.error("wireFrame/index.json 없음/비정상");
    process.exit(1);
  }

  let projectN = 0;
  let runN = 0;
  let specN = 0;
  let inputN = 0;

  for (const project of index.projects) {
    await pool.query(
      `insert into projects (slug, no, title)
         values ($1, $2, $3)
       on conflict (slug) do update
         set no = excluded.no, title = excluded.title, updated_at = now()`,
      [project.slug, project.no ?? null, project.title ?? null],
    );
    projectN += 1;

    for (const run of project.runs ?? []) {
      await pool.query(
        `insert into runs
           (run_id, project_slug, kind, no, title, status, prd_version,
            artifact_count, asset_project_slug, created_at, updated_at)
         values ($1,$2,$3,$4,$5,$6,$7,$8,$9,
                 coalesce($10, now()), coalesce($11, now()))
         on conflict (run_id) do update set
           project_slug = excluded.project_slug, kind = excluded.kind, no = excluded.no,
           title = excluded.title, status = excluded.status, prd_version = excluded.prd_version,
           artifact_count = excluded.artifact_count, asset_project_slug = excluded.asset_project_slug,
           updated_at = excluded.updated_at`,
        [
          run.runId,
          project.slug,
          run.kind ?? "wireframe",
          run.no ?? null,
          run.title ?? null,
          run.status ?? null,
          run.prdVersion ?? 1,
          run.artifactCount ?? 0,
          run.assetProjectSlug ?? null,
          run.createdAt ?? null,
          run.updatedAt ?? null,
        ],
      );
      runN += 1;

      const runDir = path.join(runsDir, run.runId);

      // PRD input(s): input/vN.md
      const inputDir = path.join(runDir, "input");
      if (fs.existsSync(inputDir)) {
        for (const file of fs.readdirSync(inputDir)) {
          const m = /^v(\d+)\.md$/.exec(file);
          if (!m) continue;
          const content = fs.readFileSync(path.join(inputDir, file), "utf8");
          await pool.query(
            `insert into run_inputs (run_id, version, content)
               values ($1,$2,$3)
             on conflict (run_id, version) do update set content = excluded.content`,
            [run.runId, Number(m[1]), content],
          );
          inputN += 1;
        }
      }

      // spec/*.json → run_specs
      const specDir = path.join(runDir, "spec");
      for (const name of SPEC_NAMES) {
        const data = readJson(path.join(specDir, `${name}.json`));
        if (data == null) continue;
        await pool.query(
          `insert into run_specs (run_id, name, data)
             values ($1,$2,$3)
           on conflict (run_id, name) do update
             set data = excluded.data, updated_at = now()`,
          [run.runId, name, JSON.stringify(data)],
        );
        specN += 1;
      }
    }
  }

  console.log(
    `imported: ${projectN} projects, ${runN} runs, ${inputN} inputs, ${specN} specs`,
  );
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
